const repo = 'https://github.com/esinocchi/jev-tool-router/blob/main';

function Figure({ name, alt, caption }: { name: 'routing-benchmark-100' | 'agent-benchmark-100'; alt: string; caption: string }) {
  return (
    <figure>
      <picture>
        <source media="(max-width: 640px)" srcSet={`/writing/jev-tool-router/${name}-mobile.svg`} />
        <img src={`/writing/jev-tool-router/${name}.svg`} alt={alt} className="h-auto w-full rounded-sm border border-border" />
      </picture>
      <figcaption>{caption}</figcaption>
    </figure>
  );
}

export function JevCaseStudy() {
  return (
    <>
      <p>AI agents often choose from a growing list of tools. Could <a target="_blank" rel="noopener noreferrer" href="https://docs.typesafe.ai/introduction">Jev</a>, a model built for structured decisions, make that choice faster and cheaper?</p>
      <aside aria-labelledby="summary-heading" className="article-summary mb-10 mt-8 border-b border-border pb-8">
        <h2 id="summary-heading" className="section-label">What I found</h2>
        <p>In the ideal-world routing test, Jev made a routing decision in 419 ms per request on average, compared with 2,459 ms for Luna, <strong>about 83% less time</strong>. The estimated cost for 100 requests was about $0.0049 with Jev and $0.037 with Luna, <strong>about 87% cheaper</strong>. In the mock agent test, Jev narrowed the tools Luna could choose from. Estimated API cost fell by <strong>about 26%</strong>, from about $0.028 to $0.021 per 100 requests. But read tasks took <strong>about 24%</strong> longer on average, rising from 3.011 to 3.737 seconds. Each figure is the median of three runs.</p>
      </aside>

      <h2>Setup</h2>
      <p>Both tests used the <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/shared_cases.json`}>same 100 synthetic prompts</a>: 47 read tasks, 21 needing approval, 13 ambiguous requests, 10 needing no tool, and 9 the tools could not handle. The 16 inert mock tools covered GitHub, browser, local files, and calendar, four each. Results are <strong>medians</strong>, with ranges below. All six <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/`}>reports</a> have complete cost data. <strong>Costs are estimates based on configured token prices, not bills.</strong></p>
      <p>The reports used <code>jev-latest</code> (responses identified <code>jev-1.13.0</code>) and <code>openai/gpt-5.6-luna</code> through OpenRouter. Requests were sequential, alternating provider or arm order by case. Jev had a three-second routing timeout; on fallback, Test 2 gave Luna all 16 tools. Luna had a 30-second timeout. Both SDKs disabled retries. The client machine and network location were not recorded. Cost estimates apply reported input and output tokens at $0.042 and $0 per million for Jev, and $0.20 and $1.20 for Luna. Test 2 includes routing and agent calls; the reports carry exact figures. Provider-native tool search was not tested, so the all-tools arm is a floor for comparison.</p>

      <h2>Test 1: The ideal world — Jev makes the routing decision</h2>
      <p>TypeSafe <a target="_blank" rel="noopener noreferrer" href="https://typesafe.ai/blog/introducing-system-one-models-and-jev">advertises</a> Jev as <strong>193.6× faster</strong> and <strong>444.6× cheaper</strong> than LLMs on its workflow benchmark, while noting these figures are likely at the high end of real-world gains. An API can force a named tool with <code>tool_choice</code>, but the LLM still generates its arguments; the agent decides whether to call a tool and when to stop. I built <a target="_blank" rel="noopener noreferrer" href={`${repo}/README.md`}>Jev Tool Router</a> to measure routing separately, then test calling Jev before the main LLM.</p>
      <p>Jev and Luna each chose a tool for every prompt; no agent call followed. <strong>Tool fit</strong> means the selected tool suited the request. It was measured on 81 prompts with an acceptable tool and <strong>does not measure task success</strong>; some prompts still needed clarification.</p>
      <p>Both routers received the same request state, options, yes/no questions, two-stage process, and decision thresholds. Luna received a system prompt and strict JSON output format requiring a choice, probabilities, confidence, and yes/no judgments; Jev used corresponding Choice and Noul questions. Neither request specified temperature or maximum tokens. The repo does not record comparative tuning effort.</p>
      <Figure name="routing-benchmark-100" alt="Three-run routing medians: Jev tool fit 76 of 81 versus Luna 77 of 81; mean routing latency 419 versus 2,459 milliseconds; estimated cost per 100 prompts $0.00486 versus $0.03673." caption="Standalone routing on the shared 100 prompts. Values are medians of three runs." />
      <p>Jev chose a suitable tool for a median <strong>76 of 81</strong> requests (range 76–76); Luna did so for <strong>77 of 81</strong> (76–77). Jev took <strong>419 ms</strong> per request at the median (run averages 405–426 ms), versus <strong>2,459 ms</strong> for Luna (2,383–2,539 ms). Estimated cost per 100 requests was <strong>about $0.0049</strong> ($0.00484–$0.00486) versus <strong>about $0.037</strong> ($0.03658–$0.03685).</p>
      <p>Jev was faster and cheaper in all <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run1-2026-09-20.json`}>three</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run2-2026-09-20.json`}>routing</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run3-2026-09-20.json`}>runs</a>. It tied Luna on tool fit once and trailed by one case twice. Jev produced fewer correct routes ready to execute: 41 (range 41–41) versus 46 (45–46). Tool fit and readiness are different judgments.</p>

      <h2>Test 2: A mock agent — Jev filters tools before Luna</h2>
      <p>This is what can be built today. One version offered Luna all 16 mock tools. The other called Jev before each turn and offered Luna its selected tool, no tool, or the full list on fallback. Luna still chose whether to call a tool and answered the prompt. Both versions used the same prompts and inert mock results; no external service ran.</p>
      <p>Both arms used the same Luna model, instructions, context, tool schemas, mock results, and four-turn limit. Luna used automatic tool choice, with no explicit temperature, response format, or maximum token count.</p>
      <Figure name="agent-benchmark-100" alt="Three-run agent medians: read-task success 37 of 47 with Jev filtering versus 35 of 47 with all tools; mean read-task latency 3.737 versus 3.011 seconds; estimated total cost per 100 prompts $0.02096 versus $0.02847." caption="Jev filtering before Luna versus offering Luna all tools, using the same 100 prompts in three paired runs." />
      <p>On 47 read tasks, the Jev arm succeeded on a median <strong>37</strong> (range 36–37), versus <strong>35</strong> with all tools (35–38). The all-tools arm won one run, 38 to 37, so Jev did <strong>not</strong> improve success consistently. Across all 100 prompts, median successful outcomes were 62 (60–63) with Jev and 55 (54–56) with all tools.</p>
      <p>Mean read-task latency was <strong>3.737 seconds</strong> with Jev at the median (range 3.565–4.001), versus <strong>3.011 seconds</strong> with all tools (2.842–3.204), an increase of <strong>about 24% from the all-tools median</strong>. Jev was slower in every run. These means include failed attempts. Across all 100 prompts, mean latency was 2.488 seconds (2.381–2.629) versus 2.340 (2.191–2.481).</p>
      <p>Estimated cost per 100 requests fell to <strong>about $0.021</strong> with Jev ($0.02081–$0.02114), from <strong>about $0.028</strong> with all tools ($0.02841–$0.02934): about <strong>26% less at the medians</strong>. Jev cost less in all <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run1-2026-09-20.json`}>three</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run2-2026-09-20.json`}>agent</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run3-2026-09-20.json`}>runs</a>.</p>
      <p>Jev asked for clarification on 12 of 13 ambiguous requests in every run, versus 6–7 with all tools. The shorter tool list itself may make Luna more likely to ask, so this may not be a router effect. Both arms struggled with approval cases (2–4 of 21 successes with Jev; 2–3 with all tools) and unsupported requests (0–1 of 9; 0 of 9). These scores use simple checks, not a full review of answer quality.</p>

      <h2>What I take from this</h2>
      <p>To me, these results suggest a place for specialist models alongside general LLMs in agents. In the routing-only test, Jev took <strong>about 83% less time</strong> and cost an estimated <strong>87% less</strong> than Luna at the medians. That does not show how Jev would perform as a model&apos;s native tool router. In the mock agent test, Jev lowered estimated API cost by about <strong>26%</strong> but increased read-task latency by about <strong>24%</strong>, with no consistent gain in completed tasks. I would be cool to test a setup where the routing step itself - the decision being made to call a specific tool - can be configured, whether through a provider API or an open-source agent stack.</p>
      <p>This was a small test with synthetic prompts, 16 inert tools, simple answer checks, and three runs. Test 1 routed only the initial prompt; real agents choose tools again as results arrive. Test 2 used a bounded mock loop, not real services. More tools might strengthen the case for prefiltering, while the extra routing call takes a larger share of latency with only 16. I did not test provider-native tool search, a stronger baseline than the all-tools arm. These results do not establish statistical significance or predict production performance.</p>
      <p>The <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/README.md`}>experiment guide</a> has the methods and reports. Earlier <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-2026-09-20.json`}>1.5-second routing</a> and <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-run1-2026-09-20.json`}>agent</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-run2-2026-09-20.json`}>reports</a> are historical; those agent runs lacked complete Jev cost data. Older <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-2026-09-20.json`}>86-request routing</a> and <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-2026-09-20.json`}>ten-task agent</a> tests used different requests. I have not mixed them into these results.</p>
    </>
  );
}
