const repo = 'https://github.com/esinocchi/jev-tool-router/blob/main';

function Figure({ name, alt, caption }: { name: 'routing-benchmark-100' | 'agent-benchmark-100'; alt: string; caption: string }) {
  return (
    <figure>
      <picture>
        <source media="(max-width: 640px)" srcSet={`/writing/jev-tool-router/${name}-mobile.svg`} />
        <img src={`/writing/jev-tool-router/${name}.svg`} alt={alt} className="h-auto w-full rounded-sm border border-border" />
      </picture>
      <figcaption>{caption}</figcaption>
    </figure>
  );
}

export function JevCaseStudy() {
  return (
    <>
      <p>Before an AI agent can answer, it may need to choose from a long list of tools. Searching your google calendar, web search, file search... the list goes on. Could <a target="_blank" rel="noopener noreferrer" href="https://docs.typesafe.ai/introduction">Jev</a>, a model built for structured decisions rather than prose, make that choice faster and more cheaply? TypeSafe <a target="_blank" rel="noopener noreferrer" href="https://typesafe.ai/blog/introducing-system-one-models-and-jev">advertises</a> Jev as <strong>193.6× faster</strong> and <strong>444.6× cheaper</strong> than LLMs on its workflow benchmark, while noting that these figures are likely at the high end of real-world gains. Ideally, I would delegate an LLM&apos;s native tool selection to Jev, but current APIs do not expose a way to replace that decision. So I built <a target="_blank" rel="noopener noreferrer" href={`${repo}/README.md`}>Jev Tool Router</a> to measure routing alone, then test the integration available today: calling Jev before the main LLM.</p>
      <p>Both tests used the <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/shared_cases.json`}>same 100 synthetic prompts</a>: 47 read tasks, 21 needing approval, 13 ambiguous requests, 10 needing no tool, and 9 the tools could not handle. I ran each test 3 times with a three-second Jev routing timeout. Results below are <strong>medians</strong> (the middle of three runs), with ranges from lowest to highest. All six <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/`}>reports</a> have complete cost data. <strong>Costs are estimates based on configured token prices, not bills.</strong></p>
      <aside aria-labelledby="summary-heading" className="article-summary mb-10 mt-8 border-b border-border pb-8">
        <h2 id="summary-heading" className="section-label">TL;DR</h2>
        <p>Jev routed prompts quickly and cheaply on its own. In the agent setup available today, Jev filtering cut estimated API cost by about 26% at the medians, but increased read-task latency.</p>
      </aside>

      <h2>Test 1: The ideal world — Jev makes the routing decision</h2>
      <p>Because I could not replace an LLM&apos;s native tool-selection step, I measured that decision separately. Jev and Luna (<code>openai/gpt-5.6-luna</code>) each chose a tool for every prompt; no agent call followed. <strong>Tool fit</strong> asks whether the selected tool was suitable on 81 prompts with an acceptable tool. It <strong>does not measure task success</strong>; some prompts still needed clarification.</p>
      <Figure name="routing-benchmark-100" alt="Three-run routing medians: Jev tool fit 76 of 81 versus Luna 77 of 81; mean routing latency 419 versus 2,459 milliseconds; estimated cost per 100 prompts $0.00486 versus $0.03673." caption="Standalone routing on the shared 100 prompts. Values are medians of three runs." />
      <p>Jev chose a suitable tool for a median <strong>76 of 81</strong> requests (range 76–76); Luna did so for <strong>77 of 81</strong> (76–77). Jev took <strong>419 ms</strong> per request at the median (run averages 405–426 ms), versus <strong>2,459 ms</strong> for Luna (2,383–2,539 ms). Estimated cost per 100 requests was <strong>$0.00486</strong> ($0.00484–$0.00486) versus <strong>$0.03673</strong> ($0.03658–$0.03685).</p>
      <p>Jev was faster and cheaper in all <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run1-2026-09-20.json`}>three</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run2-2026-09-20.json`}>routing</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-3000ms-run3-2026-09-20.json`}>runs</a>. It tied Luna on tool fit once and trailed by one case twice. But Jev produced fewer correct routes ready to execute: 41 (range 41–41) versus 46 (45–46). Selecting a suitable tool and deciding to proceed are different judgments.</p>

      <h2>Test 2: The practical world — Jev filters tools before Luna</h2>
      <p>Next I tested what an application can build today. One version offered Luna all 16 mock tools. The other called Jev first and offered Luna the tools Jev selected. Luna still made its own tool choice and answered the prompt. If Jev could not route it, Luna got the full list. Both versions saw the same prompts and inert mock results; no external service ran.</p>
      <Figure name="agent-benchmark-100" alt="Three-run agent medians: read-task success 37 of 47 with Jev filtering versus 35 of 47 with all tools; mean read-task latency 3.737 versus 3.011 seconds; estimated total cost per 100 prompts $0.02096 versus $0.02847." caption="Jev filtering before Luna versus offering Luna all tools, using the same 100 prompts in three paired runs." />
      <p>On 47 read tasks, the Jev arm succeeded on a median <strong>37</strong> (range 36–37), versus <strong>35</strong> with all tools (35–38). Yet the all-tools arm won one run, 38 to 37, so Jev did <strong>not</strong> improve success consistently. Across all 100 prompts, median successful outcomes were 62 (60–63) with Jev and 55 (54–56) with all tools.</p>
      <p>The tradeoff was time versus cost. Mean read-task latency was <strong>3.737 seconds</strong> with Jev at the median (range 3.565–4.001), versus <strong>3.011 seconds</strong> with all tools (2.842–3.204). Jev was slower in every run. These means include failed attempts. Across all 100 prompts, mean latency was 2.488 seconds (2.381–2.629) versus 2.340 (2.191–2.481).</p>
      <p>Estimated cost per 100 requests fell to <strong>$0.02096</strong> with Jev ($0.02081–$0.02114), from <strong>$0.02847</strong> with all tools ($0.02841–$0.02934): about <strong>26% less at the medians</strong>. Jev cost less in all <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run1-2026-09-20.json`}>three</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run2-2026-09-20.json`}>agent</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-3000ms-run3-2026-09-20.json`}>runs</a>.</p>
      <p>The prompt types also mattered. Jev asked for clarification on 12 of 13 ambiguous requests in every run, versus 6–7 with all tools. Both arms struggled with approval cases (2–4 of 21 successes with Jev; 2–3 with all tools) and unsupported requests (0–1 of 9; 0 of 9). These scores come from simple checks, not a full review of answer quality.</p>

      <h2>What I take from this</h2>
      <p>The routing-only test suggests Jev can select tools quickly and cheaply. It cannot tell us how Jev would perform as part of a provider&apos;s native tool calling; that integration is unavailable. In the practical agent setup, Jev lowered estimated API cost by about <strong>26% at the medians</strong> but increased read-task latency. Success varied across runs, so I cannot claim a consistent improvement in completed tasks.</p>
      <p>This was a small test with synthetic, non-held-out prompts, four tools per domain, inert mock results, and checks for literal facts in answers. Three runs show variation but do not establish statistical significance or predict production performance. I did not compare provider-native tool search or real integrations. Next I would try held-out tasks, more tools, representative results, and a native tool-search baseline.</p>
      <p>The <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/README.md`}>experiment guide</a> has the methods and reports. Earlier <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-shared-100-2026-09-20.json`}>1.5-second routing</a> and <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-run1-2026-09-20.json`}>agent</a> <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-shared-100-run2-2026-09-20.json`}>reports</a> are historical; those agent runs lacked complete Jev cost data. Older <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/routing-2026-09-20.json`}>86-request routing</a> and <a target="_blank" rel="noopener noreferrer" href={`${repo}/experiments/published/agent-bench-2026-09-20.json`}>ten-task agent</a> tests used different requests. I have not mixed them into these results.</p>
    </>
  );
}
